### ISSUE TITLE
Extract token from AST node

### ISSUE THREAD

**Issue by calebtung** [PurdueDualityLab/deepbugs-jr#1]
Given any AST node as a JSON string, extract the token and return a string.  This token is what will get passed through Word2Vec to become a vector.

**LOGIC** (more examples in Section 2.4)
For a given AST NODE n
- If n is an identifier `{ "id":4, "type":"Identifier", "value":"console" }`, return its name `ID:console`.
- If n is a literal `{ "id":6, "type":"LiteralString", "value":"hello" }`, return a string representation of its value `LIT:hello`.
- If n is a this expression, return `LIT:this`.
- If n is an update expression that increments or decrements x, return name (x).
- If n is a member expression base.prop that accesses a property, return name (prop).
- If n is a member expression base[k] that accesses an array element, return name (base).
- If n is a call expression base.callee (..), return name (callee).
- For any other AST node n, do not extract its name.

returns string of token

**Comment by Jmw150** [comment]
Section 2.4 of the paper described processing tokens from raw javascript code. So a slightly different strategy was needed.
