### ISSUE TITLE
Setup GitHub CI with Python unit testing capability

### ISSUE THREAD

**Issue by calebtung** [PurdueDualityLab/deepbugs-jr#11]
https://medium.com/swlh/automate-python-testing-with-github-actions-7926b5d8a865 might be a good start?

**Comment by ugaldedr** [comment]
Initial pipeline is good to go. Verified it checkouts out code and runs the deepbugs-jr.py file. As the project progresses we will integrate test cases to verify our code.

**Comment by ugaldedr** [comment]
I've added a test job that makes use of the [unittest](https://docs.python.org/3/library/unittest.html) module.

**Comment by ugaldedr** [comment]
Had to modify the file structure for the project. Github CI did not take kindly to having a src directory so now the files are in the top level of the repo.

**Comment by calebtung** [comment]
LGTM!
