### ISSUE TITLE
Acquire and prep code corpus

### ISSUE THREAD

**Issue by yjung199** [PurdueDualityLab/deepbugs-jr#2]
JavaScript dataset that the original authors has used is [here](https://www.sri.inf.ethz.ch/js150).

Push a selection of ASTs to GitHub.

**Comment by yjung199** [comment]
Each bug detectors that Deepbugs features are:
1. Swapped function arguments
2. Wrong binary operation
3. Wrong operand in binary operation

**Comment by ugaldedr** [comment]
Refer to section 2.1 of _DeepBugs_ as source of this task.

**Comment by calebtung** [comment]
Updated with 10 AST files directly pushed onto `develop` branch
