### ISSUE TITLE
swarg: Early test - Generate training/eval dataset

### ISSUE THREAD

**Issue by yjung199** [PurdueDualityLab/deepbugs-jr#3]
Using the function calls from Issue #10 and Word2Vec token-to-vector system from Issue #5, generate a full training/eval dataset for the JavaScript code corpus.

Something like:
```python

positiveExample = Word2Vec(Token(fnName)) + Word2Vec(Token(arg1)) + Word2Vec(Token(arg2))
negativeExample = Word2Vec(Token(fnName)) + Word2Vec(Token(arg2)) + Word2Vec(Token(arg1))

```

**Comment by ugaldedr** [comment]
Refer to section 2.2, 2.3, 2.4 of _DeepBugs_ as source of this task.

**Comment by calebtung** [comment]
Generated as two .npz files: https://1drv.ms/u/s!AvvT9f1RiwGbh6oOfzezjBOaXrCmIw?e=8C1yj1
