### ISSUE TITLE
swarg: Build Bug detector NN

### ISSUE THREAD

**Issue by ugaldedr** [PurdueDualityLab/deepbugs-jr#4]
**NETWORK ARCHITECTURE**
INPUT (Dropout 20%)
HIDDEN (Dense 200 + ReLU + Dropout 20%)
OUTPUT (Dense 1 + Sigmoid)

Compile w `binary_crossentropy` loss and the `rmsprop` optimizer.
Train for 10 epochs. Batch size 100

**Comment by ugaldedr** [comment]
Refer to section 2.5 of DeepBugs as source of this task.

**Comment by calebtung** [comment]
LGTM!
